### ISSUE TITLE
Editing SVG does not save meta data properly

### ISSUE THREAD

**Issue by bryce13950** [tsub/s3-edit#12]
An existing SVG with a Content-Type set to image/svg+xml is being set binary/octet-stream upon save, which is in turn causing SVGs to be downloaded instead of displayed in a browser.

**Comment by tsub** [comment]
Thank you for a bug report.

Probably related to Issue below (In terms of implementation).

Issue https://github.com/tsub/s3-edit/issues/8

**Comment by bryce13950** [comment]
Potentially, is there a way to store an items meta information, and then save it after the editing is complete?

**Comment by tsub** [comment]
Yes, we can get meta information when downloading objects from S3 with GetObject API.
Of course, aws-sdk-go is also possible.

> ```
>     // A standard MIME type describing the format of the object data.
>     ContentType *string `location:"header" locationName:"Content-Type" type:"string"`
>     ...
>     // A map of metadata to store with the object in S3.
>     Metadata map[string]*string `location:"headers" locationName:"x-amz-meta-" type:"map"`
> ```
>
> https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#GetObjectOutput

**Comment by tsub** [comment]
This issue is fixed in PR https://github.com/tsub/s3-edit/pull/16 and released in [v0.0.11](https://github.com/tsub/s3-edit/releases/tag/v0.0.11).
Please check whether the problem is solved.

**Comment by bryce13950** [comment]
Thanks a ton!
