### ISSUE TITLE
Warning: Calling bottle :unneeded is deprecated!

### ISSUE THREAD

**Issue by milosivanovic** [tsub/s3-edit#20]
Recently, brew has started spitting out this message:

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the tsub/s3-edit tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/tsub/homebrew-s3-edit/s3-edit.rb:6
```

As seen below:
```
milos@air:~$ brew upgrade
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 4 formulae.
==> Updated Casks
Updated 11 casks.
Updating Homebrew...
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the tsub/s3-edit tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/tsub/homebrew-s3-edit/s3-edit.rb:6
```

Could you help silence this warning by not calling `bottle :unneeded` as suggested?

**Comment by tsub** [comment]
@milosivanovic I have just released [v0.0.14](https://github.com/tsub/s3-edit/releases/tag/v0.0.14) to fix the problem.
(I actually [solved the problem](https://github.com/goreleaser/goreleaser/pull/2591) by releasing it using a version of goreleaser that fixed the problem. The Homebrew Formula diff is https://github.com/tsub/homebrew-s3-edit/commit/f71d1458514c62eb9a02d56854f526df6829a8c6.)

Please try to run `$ brew upgrade`.

Thanks for reporting the issue!
