### ISSUE TITLE
Ability to specify profile via command line

### ISSUE THREAD

**Issue by jdavidbakr** [tsub/s3-edit#9]
Thanks for this tool! Found it today while looking for a way to easily edit s3 files.

Unless I am misunderstanding, you have to make sure the env variables are set for the profile and region.  I use the `aws` command with multiple profiles using the `--profile` flag, it would be great if this tool included a similar option.

**Comment by tsub** [comment]
Thank you for a good idea :smile:
It seems easy, so I will implement it soon.
